site_name: API Design Systems
repo_url: https://github.com/smizell/api-design-systems
repo_name: smizell/api-design-systems
edit_uri: edit/main/docs
theme:
  name: material
  features:
    - navigation.instant
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Overview: index.md
  - guidelines.md
  - specification.md
  - principles.md
  - standards.md
  - Example: example.md
  - changelog.md